export const jobsData = [
    {
        title: 'Product Manager',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        name: 'Leanne Graham',
        aboutMe: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        likes: 1,
        companyName: 'ABC',
        companyInfo: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
    },
    {
        title: 'Product Executive',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        name: 'Ervin Howell',
        aboutMe: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        likes: 5,
        companyName: 'ABC',
        companyInfo: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
    },
    {
        title: 'Graphic Designer',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        name: 'Clementine Bauch',
        aboutMe: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        likes: 3,
        companyName: 'ABC',
        companyInfo: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
    },
    {
        title: 'UI/UX Desiger',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        name: 'Patricia Lebsack',
        aboutMe: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        likes: 4,
        companyName: 'ABC',
        companyInfo: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
    },
    {
        title: 'Frontend Developer',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        name: 'Chelsey Dietrich',
        aboutMe: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        likes: 5,
        companyName: 'ABC',
        companyInfo: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
    },
    {
        title: 'Backend Developer',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        name: 'Dennis Schulist',
        aboutMe: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        likes: 5,
        companyName: 'ABC',
        companyInfo: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
    },
    {
        title: 'Fullstack Developer',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        name: 'Kurtis Weissnat',
        aboutMe: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        likes: 1,
        companyName: 'ABC',
        companyInfo: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
    },
    {
        title: 'Database Administrator',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        name: 'Nicholas Runolfsdottir',
        aboutMe: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        likes: 5,
        companyName: 'ABC',
        companyInfo: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
    },
    {
        title: 'Database Administrator',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        name: 'Nicholas Runolfsdottir',
        aboutMe: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        likes: 5,
        companyName: 'ABC',
        companyInfo: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
    },
    {
        title: 'Secretary',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        name: 'Glenna Reichert',
        aboutMe: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        likes: 0,
        companyName: 'ABC',
        companyInfo: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
    },
    {
        title: 'Accounts Manager',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        name: 'Clementina DuBuque',
        aboutMe: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        likes: 5,
        companyName: 'ABC',
        companyInfo: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
    },
    {
        title: 'Product Manager',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        name: 'odio adipisci',
        aboutMe: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        likes: 0,
        companyName: 'ABC',
        companyInfo: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
    },
    {
        title: 'Product Executive',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        name: 'alias odio',
        aboutMe: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        likes: 5,
        companyName: 'ABC',
        companyInfo: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
    },
    {
        title: 'Graphic Designer',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        name: 'vero eaque',
        aboutMe: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        likes: 5,
        companyName: 'ABC',
        companyInfo: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
    },
    {
        title: 'UI/UX Desiger',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        name: 'et fugit eligendi',
        aboutMe: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        likes: 3,
        companyName: 'ABC',
        companyInfo: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
    },
    {
        title: 'Frontend Developer',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        name: 'repellat consequatur',
        aboutMe: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        likes: 5,
        companyName: 'ABC',
        companyInfo: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
    },
    {
        title: 'Backend Developer',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        name: 'et omnis dolorem',
        aboutMe: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        likes: 5,
        companyName: 'ABC',
        companyInfo: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
    },
    {
        title: 'Fullstack Developer',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        name: 'provident id ',
        aboutMe: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        likes: 5,
        companyName: 'ABC',
        companyInfo: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
    },
    {
        title: 'Database Administrator',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        name: 'fugit labore',
        aboutMe: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        likes: 1,
        companyName: 'ABC',
        companyInfo: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
    },
    {
        title: 'Database Administrator',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        name: 'Oswald Vandervor',
        aboutMe: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        likes: 2,
        companyName: 'ABC',
        companyInfo: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
    },
    {
        title: 'Secretary',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        name: 'Maynard Hodkiewicz',
        aboutMe: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        likes: 5,
        companyName: 'ABC',
        companyInfo: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
    },
    {
        title: 'Accounts Manager',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        name: 'Preston Hudson',
        aboutMe: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
        likes: 3,
        companyName: 'ABC',
        companyInfo: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed facilisis magna. Donec eu augue auctor, ultrices dolor ac, fermentum dolor. Aenean orci magna, viverra ut ornare vel, consectetur ut tellus. In hac habitasse platea dictumst.',
    },
]